### ISSUE TITLE
绘图时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [17TheWord/mcqq-tool#35]
已修改字体文件权限
![image](https://github.com/user-attachments/assets/0a5644a1-0864-4227-a26b-61d78398fe78)
但还是提示无法打开字体文件
```Python
08-31 22:00:30 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=26) failed.
Traceback (most recent call last):
  File "/home/yuyue/nonebot/yuyue-nonebot/bot.py", line 22, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/yuyue/.local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/yuyue/.local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot_plugin_mcqq/qq_msg.py", line 79, in handle_qq_cmd
    temp_result = await send_command_to_target_server(event=event, command=cmd)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/send_to_mc.py", line 191, in send_command_to_target_server
    rcon_result = get_rcon_result(result=result[0], event=event)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/utils.py", line 32, in get_rcon_result
    image = draw_result_image(result)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/draw_result.py", line 89, in draw_result_image
    font = ImageFont.truetype("CascadiaCode.ttf", font_size)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 807, in truetype
    return freetype(font)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 804, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 244, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by 17TheWord** [comment]
你试试在 `mcqq_tool` -> `draw_result` 第89行，把变量 `"CascadiaCode.ttf"` 改为 `Path(__file__).parent / "CascadiaCode.ttf"`

**Comment by 17TheWord** [comment]
> 你试试在 `mcqq_tool` -> `draw_result` 第89行，把变量 `"CascadiaCode.ttf"` 改为 `Path(__file__).parent / "CascadiaCode.ttf"`

如果有效我就发版，不然改动太频繁了。不好意思没注意这块

**Comment by YuYue-Amatsuki** [comment]
> > 你试试在 `mcqq_tool` -> `draw_result` 第89行，把变量 `"CascadiaCode.ttf"` 改为 `Path(__file__).parent / "CascadiaCode.ttf"`
> 
> 如果有效我就发版，不然改动太频繁了。不好意思没注意这块

修改后依旧报错
```Python
08-31 22:41:24 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=26) failed.
Traceback (most recent call last):
  File "/home/yuyue/nonebot/yuyue-nonebot/bot.py", line 22, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/yuyue/.local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/yuyue/.local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot_plugin_mcqq/qq_msg.py", line 79, in handle_qq_cmd
    temp_result = await send_command_to_target_server(event=event, command=cmd)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/send_to_mc.py", line 191, in send_command_to_target_server
    rcon_result = get_rcon_result(result=result[0], event=event)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/utils.py", line 32, in get_rcon_result
    image = draw_result_image(result)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/draw_result.py", line 96, in draw_result_image
    lines = wrap_text(draw, segments, font, max_width)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/draw_result.py", line 67, in wrap_text
    segment_width = draw.textlength(segment.text, font=font)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageDraw.py", line 693, in textlength
    raise ValueError(msg)
ValueError: can't measure length of multiline text
```

**Comment by 17TheWord** [comment]
看样子是发了多行消息，我只处理了一行

**Comment by 17TheWord** [comment]
`pip install mcqq-tool==1.3.0.post1`

**Comment by YuYue-Amatsuki** [comment]
> `pip install mcqq-tool==1.3.0.post1`

中文字体能否调用系统自带的？
依赖包内的字体不支持中文，导致渲染结果乱码
![Image_1725163503126.png](https://github.com/user-attachments/assets/304697a2-7eae-4f8a-abf6-09abed918404)

**Comment by 17TheWord** [comment]
好家伙，我忽略了这条，等我更新成自定义字体路径，然后塞个支持中文的字体

**Comment by 17TheWord** [comment]
为什么你的命令会返回这么多颜色和中文，用的ess还是什么管理插件？

**Comment by YuYue-Amatsuki** [comment]
> 为什么你的命令会返回这么多颜色和中文，用的ess还是什么管理插件？

ess

**Comment by 17TheWord** [comment]
字体这块我是在找更偏向于MC风格的，直接问的gpt来着。现在看还是从win10里找个塞进去算了，留个配置项可以自定义字体路径

**Comment by YuYue-Amatsuki** [comment]
> 字体这块我是在找更偏向于MC风格的，直接问的gpt来着。现在看还是从win10里找个塞进去算了，留个配置项可以自定义字体路径

类似于mc风格的字体我个人更建议使用[Unifont](https://ftp.gnu.org/gnu/unifont/unifont-15.0.01/unifont-15.0.01.ttf)，并且也支持中文

**Comment by 17TheWord** [comment]
`pip install mcqq-tool==1.3.0.post2`

**Comment by YuYue-Amatsuki** [comment]
> `pip install mcqq-tool==1.3.0.post2`

能否在不填写`mc_qq__ttf_path = ""`配置项的情况下默认使用依赖包内的字体？
不填写`mc_qq__ttf_path = ""`配置项的情况下会报错，日志如下
```Python
09-01 13:33:35 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mcqq.qq_msg, lineno=26) failed.
Traceback (most recent call last):
  File "/home/yuyue/nonebot/yuyue-nonebot/bot.py", line 22, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/yuyue/.local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/yuyue/.local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot_plugin_mcqq/qq_msg.py", line 79, in handle_qq_cmd
    temp_result = await send_command_to_target_server(event=event, command=cmd)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/send_to_mc.py", line 191, in send_command_to_target_server
    rcon_result = get_rcon_result(result=result[0], event=event)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/utils.py", line 32, in get_rcon_result
    image = draw_result_image(result)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/draw_result.py", line 94, in draw_result_image
    font = ImageFont.truetype(plugin_config.ttf_path, font_size)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 807, in truetype
    return freetype(font)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 804, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/yuyue/.local/lib/python3.10/site-packages/PIL/ImageFont.py", line 244, in __init__
    self.font = core.getfont(
OSError: unknown file format
```

**Comment by 17TheWord** [comment]
`1.3.1` !
